# Generated by Django 5.1.6 on 2025-02-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_profile_picture_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='blank_user_img.png', upload_to='user_images/'),
        ),
    ]
