# Generated by Django 5.1.6 on 2025-02-25 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
