# Generated by Django 5.1.6 on 2025-03-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_img',
        ),
        migrations.AddField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='cover_images/blank_user_img.png', upload_to='cover_images/'),
        ),
    ]
