# Generated by Django 5.1.6 on 2025-03-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_user_user_img_user_cover_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(default='cover_images/cover_img.png', upload_to='cover_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/profile_img.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
